#!/usr/bin/env ruby
begin
  require File.expand_path('../.bundle/environment', __FILE__)
rescue LoadError
  require "rubygems"; require "bundler"; Bundler.setup
end

load File.expand_path('../../../bin/ey', __FILE__)