#!/usr/bin/env ruby
begin
  require File.expand_path('../.bundle/environment', __FILE__)
rescue LoadError
  Dir.chdir(File.dirname(__FILE__)) do
    require "rubygems"
    require "bundler"
    Bundler.setup
  end
end

$LOAD_PATH.unshift File.expand_path("../../../lib", __FILE__)
load File.expand_path('../../../bin/ey', __FILE__)